pipeline {
  agent any

  environment {
    ANYPOINT_CREDENTIALS = credentials('Anypoint')
  }
  tools{
      maven 'Maven_Local3.6.2'
    }
  stages {
    stage('Unit Test') { 
      steps {
        sh '/usr/local/bin/mvn -f gitproj_del/pom.xml clean test'
      }
    }
    
    stage('Deploy CloudHub') { 
      steps {
              sh '/usr/local/bin/mvn -f gitproj_del/pom.xml clean package deploy -Dmule.username=${ANYPOINT_CREDENTIALS_USR} -Dmule.password=${ANYPOINT_CREDENTIALS_PSW} -Dmule.version=4.1.4 -Dmule.URL=https://anypoint.mulesoft.com -DmuleDeploy'
      }
      //steps {
      //  sh 'mvn deploy -P cloudhub -Dmule.version=4.1.4 -Danypoint.username=${DEPLOY_CREDENTIALS_USR} -Danypoint.password=${DEPLOY_CREDENTIALS_PSW}' 
      //}
    }
  }
}
